#!/bin/sh
# $FreeBSD$

set -e

scriptdir=$(cd $(dirname $0) && pwd)
fwdir=$scriptdir/../amdgpukmsfw-files

for dir in $scriptdir/*; do
	if [ ! -d $dir ]; then
		continue
	fi
	rm -rf $dir
done

for file in $fwdir/*.bin; do
	base=$(basename $file)
	img=${base%.bin}
	echo "Image: $img"

	mkdir -p $scriptdir/$img
	cat > $scriptdir/$img/Makefile <<EOF
# \$FreeBSD$

NAME=	$img

.include <bsd.kmod.mk>
EOF
done
