# $FreeBSD$

SUBDIR= \
	bxtdmc \
	bxtguc \
	bxthuc \
	cnldmc \
	glkdmc \
	kbldmc_101 \
	kbldmc_104 \
	kblguc \
	kblhuc \
	sklguc_61 \
	sklguc_933 \
	sklhuc \
	skldmc_126 \
	skldmc_127

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
