# $FreeBSD$

SUBDIR= \
	bxtdmc_107 \
	bxtguc_929 \
	bxthuc_107 \
	cnldmc_106 \
	glkdmc_104 \
	kbldmc_104 \
	kblguc_939 \
	kblhuc_200 \
	sklguc_933 \
	sklhuc_107 \
	skldmc_127 \
	tgldmc_204

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
